name = "Amharic"
version = "0.1.0"

[macos]
system_pkg_id = "no.divvun.MacDivvun.am"

[windows]
system_product_code = "EE4FC84D-EDAC-499F-A24B-9DF157796AF9"
msoffice_product_code = "6BD6BC85-AC5B-4AC1-BFA0-48DC1D68A1F5"
