template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "amha1245"
__REPO__ = "lang-amh"
__UND2C__ = "am"
__UNDEFINED__ = "Amharic"
__UND__ = "amh"
