template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "amha1245"
__REPO__ = "lang-amh"
__UND2C__ = "am"
__UNDEFINED__ = "Amharic"
__UND__ = "amh"
